# The Site Configuration
theme: jekyll-theme-chirpy

lang: en
timezone: Asia/Jakarta

title: Astri Cahyani
tagline: astri's tech corner ||  a learning log of my journey in tech from data, cloud, ai and everything in between
description: astri's learning log and tech corner on data, ai, cloud or anything

url: "https://kidkicu.github.io"

github:
  username: kidkicu

twitter:
  username: kicucodes

social:
  name: Astri Cahyani
  email: astricahyani2@gmail.com
  links:
    - https://twitter.com/kicucodes
    - https://github.com/kidkicu
    - https://www.linkedin.com/in/astricahyani

avatar: https://ibb.co.com/d4rkXwyY
# ... rest of config
